openapi: 3.0.0
servers:
  - url: http://localhost:3000
    description: Localhost Environment
    
info:
  version: '1.0.0'
  title: Restaurant API
  description: >-
    Restaurant API documentation

components:
  responses:
    200_Login:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              user_id:
                type: string
                example: 5f8db309216bebdc870c8d0b
              token:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmOGRiMzA5MjE2YmViZGM4NzBjOGQwYiIsInBlcm1pc3Npb25zIjpbImZpbmFuY2Vyc19yZWFkIiwiZmluYW5jZXJzX2NyZWF0ZSIsImZpbmFuY2Vyc191cGRhdGUiLCJmaW5hbmNlcnNfZGVsZXRlIiwicHJvZmVzc2lvbnNfcmVhZCIsInByb2Zlc3Npb25zX2NyZWF0ZSIsInByb2Zlc3Npb25zX3VwZGF0ZSIsInByb2Zlc3Npb25zX2RlbGV0ZSIsInByb2Zlc3Npb25hbHNfcmVhZCIsInByb2Zlc3Npb25hbHNfY3JlYXRlIiwicHJvZmVzc2lvbmFsc191cGRhdGUiLCJwcm9mZXNzaW9uYWxzX2RlbGV0ZSJdfSwiaWF0IjoxNjAzMzkwNDk1LCJleHAiOjE2MDMzOTEwOTV9.h4IYU0T35a7GmFB4Higpmf4Nowjie0jnszX-KO6aCsQ
              expires_in:
                type: integer
                example: 3600
    400_Bad_Request:
      description: Error processing request
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  name:
                    type: string
                    example: 'ValidationError'
                  message:
                    type: string
                    example: '"email" is required'
    401_Authorization_Denied:
      description: Authorization information is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Token expired'
paths:
  /menus:
    get:
      summary: Get all menus
      responses:
        '200':
          $ref: '#/components/responses/200_Login'
        '400':
          $ref: '#/components/responses/400_Bad_Request'
  /categories:
    get:
      summary: Get all menus
      responses:
        '200':
          $ref: '#/components/responses/200_Login'
        '400':
          $ref: '#/components/responses/400_Bad_Request'
